### ISSUE TITLE
Can't create library from the nt.fasta file

### ISSUE THREAD

**Issue by advaitb** [PathoScope/PathoScope#16]
Hi,

I've been trying to run Pathoscope 2.0 (installed through conda in a separate env) to create a library as given in the wiki, but it gives me the error below, not sure if it has shown up as an issue before.

`tail: cannot open './ncbiDB/gi_taxid_nucl.dmp' for reading: No such file or directory
Traceback (most recent call last):
  File "/home/Users/ab114/miniconda3/envs/pathoscope/bin/pathoscope", line 10, in <module>
    sys.exit(main())
  File "/home/Users/ab114/miniconda3/envs/pathoscope/lib/python2.7/site-packages/pathoscope/pathoscope2.py", line 235, in main
    inputArgs.lib_outdir)
  File "/home/Users/ab114/miniconda3/envs/pathoscope/lib/python2.7/site-packages/pathoscope/patholib/pathoLib.py", line 93, in append_ti_into_fasta_app
    valSel, invalSel, invalSelFlag)
  File "/home/Users/ab114/miniconda3/envs/pathoscope/lib/python2.7/site-packages/pathoscope/patholib/pathoLib.py", line 500, in append_ti_into_fasta_hash
    (maxGi,gi2ti)=gi2tax_list(gi2taxFn)
  File "/home/Users/ab114/miniconda3/envs/pathoscope/lib/python2.7/site-packages/pathoscope/patholib/pathoLib.py", line 118, in gi2tax_list
    mxGi=read_gi_taxid_nucldmp_max(gi2taxDump)
  File "/home/Users/ab114/miniconda3/envs/pathoscope/lib/python2.7/site-packages/pathoscope/patholib/pathoLib.py", line 143, in read_gi_taxid_nucldmp_max
    mxGi=int(msg.strip())
ValueError: invalid literal for int() with base 10: ''`

**Comment by VanishingRasengan** [comment]
@advaitb Did you find a solution for this problem? I have the same error running Pathoscope 2.0!
